-- 코드를 입력하세요
SELECT  ZZ.FLAVOR AS FLAVOR FROM (
SELECT SUM(Z.TOTAL_ORDER) AS TOTAL_ORDER , Z.FLAVOR AS FLAVOR  FROM (
SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR AS FLAVOR FROM FIRST_HALF GROUP BY FLAVOR
UNION ALL
SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR AS FLAVOR FROM JULY GROUP BY FLAVOR ) Z
GROUP BY FLAVOR ORDER BY TOTAL_ORDER DESC LIMIT 3  ) ZZ