WITH RECURSIVE cte (a) AS
(
  SELECT 0
  UNION ALL
  SELECT a + 1 FROM cte WHERE a < 23
)
SELECT a AS HOUR, COUNT(ANIMAL_ID) as COUNT
FROM cte LEFT JOIN ANIMAL_OUTS ON a = HOUR(DATETIME)
GROUP BY a
ORDER BY a