-- 코드를 작성해주세요

-- SELECT * FROM FISH_NAME_INFO
-- SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO A, FISH_NAME_INFO B WHERE 
-- A.FISH_TYPE = B.FISH_TYPE AND 
-- A.FISH_TYPE IN (0, 1)
SELECT * FROM FISH_INFO