-- 코드를 작성해주세요
-- SELECT * FROM HR_DEPARTMENT
-- SELECT * FROM HR_EMPLOYEES
SELECT Z.SCORE, Z.EMP_NO, Z.EMP_NAME, Z.POSITION, Z.EMAIL  FROM (
SELECT C.EMP_NO AS EMP_NO, B.EMP_NAME AS EMP_NAME, SUM(C.SCORE) AS SCORE, B.POSITION AS POSITION, B.EMAIL AS EMAIL FROM HR_DEPARTMENT A INNER JOIN HR_EMPLOYEES  B 
ON A.DEPT_ID = B.DEPT_ID INNER JOIN HR_GRADE C 
ON B.EMP_NO = C.EMP_NO GROUP BY EMP_NO
    ORDER BY SCORE DESC LIMIT 1 ) Z